### ISSUE TITLE
Please document jruby.runtime.arguments

### ISSUE THREAD

**Issue by cky** [jruby/jruby-rack#130]
Similar to kares (who wrote the patch that introduced `jruby.runtime.arguments` in jruby/jruby-rack#62), I am having to add command-line arguments to enable profiling. But I've had to discover `jruby.runtime.arguments` in the source, because it doesn't appear to be documented anywhere.

I noticed that the README documents most of the properties you can set. Please add `jruby.runtime.arguments` to this list.

**Comment by stu-blair** [comment]
+1 !

I'm trying to enable the `reify.classes` argument so that I can analyze a heapdump from my application with the ruby objects 'reified' (informatively named). 

After discovering `jruby.runtime.arguments`, I thought I had my answer, but it just doesn't seem to work. I tried this:
```
  <context-param>
    <param-name>jruby.runtime.arguments</param-name>
    <param-value>-Xreify.classes=true</param-value>
  </context-param>
```

Which gives this error: `org.jruby.rack.RackInitializationException: org.jruby.exceptions.MainExitException: jruby: invalid extended option reify.classes=true`

I've also tried `-Xjruby.reify.classes=true` (similar error)
And various other formulations like `-J-Djruby.reify.classes=true` , which don't give errors, but don't seem to be actually enabling the argument.

Am I specifying the command wrong? Is there any other way to enable this argument in JRuby-Rack ? (I'm using jruby 1.7.26 and jruby-rack 1.1.16.)

**Comment by kares** [comment]
@stu-blair that is the (main) reason why this is not documented - it won't work for any of the properties!
actually a quite small sub-set it does smt. use System properties for those (`-Djruby.reify.classes=true`).

**Comment by stu-blair** [comment]
thanks @kares ! i did eventually figure out a different way of specifying the argument, like you suggested. 

It does seem like if it was documented, I would have known about its limited functionality and known not to use it.

**Comment by kares** [comment]
I think I will remove it completely at some point -> this is just going places really not intented by the 'hack'.

**Comment by ketan** [comment]
> I think I will remove it completely at some point -> this is just going places really not intented by the 'hack'.

I know this is closed, but perhaps including a hook, probably into the `org.jruby.rack.RackFilter` or `RailsServletContextListener` for users to subclass and provide their own runtime (or parameters to runtime) might be useful?
